# Generated by Django 3.1.1 on 2020-12-26 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GameSite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game', models.CharField(max_length=200)),
                ('url', models.CharField(max_length=200)),
                ('have_played', models.BooleanField()),
                ('min_players', models.IntegerField(default=0)),
                ('max_players', models.IntegerField(default=0)),
                ('is_intrigue', models.BooleanField()),
                ('notes', models.TextField()),
            ],
        ),
    ]
