# Generated by Django 3.1.1 on 2020-12-26 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boardgames', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamesite',
            name='donation_url',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
