# Generated by Django 3.1.1 on 2020-12-26 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boardgames', '0002_gamesite_donation_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamesite',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
